### ISSUE TITLE
How can you handle icons using fzf?

### ISSUE THREAD

**Issue by tbrodbeck** [AhmedAbdulrahman/dotfiles#5]
Hey I read your recent medium post about fzf. Really awesome stuff. Thank you! I left a comment there, but apparently you did not see it, that's why I try to reach for you out one last time via GitHub.

I could get everything to work but one thing: 

The preview icons on the left side of the files can be displayed, but I did not find a way to exclude them from my search results.  (https://miro.medium.com/max/2240/1*Cizs8B5okJSqPwxrd364VQ.gif)

The preview box is not working anymore as well (For example it gives me the error `[bat error]: ' Desktop/01_Introduction.pdf': No such file or directory (os error 2)`)

How did you work around this issue?
Best, Till

**Comment by AhmedAbdulrahman** [comment]
Hey, 
Thanks for reaching out, sorry I might missed your comment.

If you want to get rid of icons fron FZF do the following:

- Remove iconful plugin `zplug 'wfxr/iconful', as:command, use:'(iconful).sh', rename-to:'$1', from:github` from `zplug`
- Remove ` | iconful -f` and `| iconful -d ` from env variables 
these 👇
```bash
    export FZF_CTRL_T_COMMAND="${__FZF[CMD]} | iconful -f "
    export FZF_ALT_C_COMMAND="${__FZF[ALT_C]} | iconful -d"
    export FZF_ALT_E_COMMAND="${__FZF[ALT_E]} | iconful -f"
```

regarding the `bat` error I havn't seen it before but try to pull the latest copy of my dotfiles it should work fine :) 

@tbrodbeck
